remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: microBioRust, a microbial bioinformatics crate
domain: LCrossman.github.io
url: https://LCrossman/github.io
baseurl: /microBioRust_details/
logo: crab_magnifying.jpeg
